#!/usr/bin/env bash
# Create a linkified vimwiki tree of the specified directory and subdirectories.
# It takes one argument: the base directory of the vimwiki.
# For the links to make sense, save the output of this script into a file located in this base directory.
# This script requires `tree` to be installed.

#TODO test for taskwiki envars
wikiroot=".task/wiki"
cd ~/"$wikiroot"

# Print header
echo '= Taskwiki Index ='
while IFS='' read -r line; do
  # Assuming there are no files with ── in their name.
  filename="$(<<<"$line" sed -r 's/.*── (.*)/\1/' )"
  treetrunk="$(<<<"$line" sed -r 's/(.*── ).*/\1/')"
  wikiname=$(echo "$filename" | cut -d. -f1 | sed 's;\/\/$;\/;g')
  wikidir=$(echo "$filename" | cut -d. -f2 | sed 's;\/\/$;\/;g')
#TODO  desc=$(awk ...)
  filepath="$(echo "${wikidir}/${filename}" | sed 's;\/\/$;\/;g')"
#filepath="~/${wikiroot}/${wikidir}/${filename}"
# desc=$(echo -e "\t\tDescription")
desc=$(echo -e "\t\t$(grep 'Description\s\+::' $filepath |cut -d ':' -f 3)")
#desc=$(awk -f /home/djp/tmp/taskwiki-utils/def-desc.awk < ${filepath})
  # Calculate depth of current file, where 1 is current directory.
  depth=$(( $(<<<"$treetrunk" wc -m ) / 4 ))

  # Work out path
  path_array[$depth]="$filename"
  path_formatted="$(printf "/%s" "${path_array[@]:1:$depth}")"
  path_formatted="${path_formatted:1}"

  # Print out line
  if $(<<<"$filename" grep -q '.wiki$'); then
    echo -e "- [[/$wikidir/${filename%.wiki}|${wikiname}]] ${desc}"
  elif $(<<<"${filename}" grep -q '/$'); then
    echo -e "== [[/${wikidir}index|${wikiname}]] == ${desc}" | sed 's;\/\/$;\/;g'
  else
    echo "$filename"
  fi
done <<< "$(tree -F -P '*.wiki' -I '*index.wiki|*_html|*~*' | head -n -3 | tail -n +2)"

echo "filepath = ${filepath}"
echo "wikiname = ${wikiname}"
echo "filename = ${filename}"
echo "desc = ${desc}"
echo "# vim:foldlevel=3"
